### ISSUE TITLE
May I ask how to generate large-size LP problem

### ISSUE THREAD

**Issue by luzai** [simonbowly/lp-generators#1]
Hi simonbowly, 

Thank you for the great work! May I ask how to generate large-size LP problem? For example, the number of variables is more than 1M.

I guess one bottleneck is Dense LHS matrix. Theoretically, is it possible that the LP problems can be generated using sparse LHS matrix? 

Thank you!

Best,
luzai

**Comment by luzai** [comment]
May I ask about the followup about lhs_generators.py? I saw the comments `further work needed (equivalent efficient algorithm and/or C++ implementation) before using this for larger instances.` 

Thank you!

**Comment by simonbowly** [comment]
Hi @luzai, sorry for the delay. I haven't touched this code in quite a few years now, but yes, to support larger problems some internals need a rewrite to hold sparse matrices instead of dense matrices.

The generators already produce sparse matrices, what needs to be done is replacing the `construct_dense_canonical` with an equivalent sparse path into the CLP data structures. I doubt I'll have time to do that in the near future, but happy to take a look at a PR.

**Comment by luzai** [comment]
Hi simonbowly, 

Thank you for your reply. One of ways to speedup is by numba for lhs_generators. I can submit PR for this when I have time.

Best,
luzai

**Comment by luzai** [comment]
Hi simonbowly,

I put my version with numba [here](https://github.com/luzai/lp-generators/tree/use-numba). The speedup happens for generator producing sparse matrices you mentioned (python for loop --> numba jit). Not yet touch the later-on 'construct_dense_canonical ' you mentioned. Since I heavily modified the code, and not yet fully test the correctness, I will wait for your comment and then decide whether to submit PR. 

Best,
luzai
